/// Derslerin, şemaların ve ekran okuyucu etiketlerinin paylaştığı adlar.
const sharedContentTr = <String, String>{
  'intervalName.perfect-unison': 'Tam Birli',
  'intervalName.minor-second': 'Küçük 2\'li',
  'intervalName.major-second': 'Büyük 2\'li',
  'intervalName.minor-third': 'Küçük 3\'lü',
  'intervalName.major-third': 'Büyük 3\'lü',
  'intervalName.perfect-fourth': 'Tam 4\'lü',
  'intervalName.augmented-fourth': 'Artık 4\'lü',
  'intervalName.diminished-fifth': 'Eksik 5\'li',
  'intervalName.perfect-fifth': 'Tam 5\'li',
  'intervalName.minor-sixth': 'Küçük 6\'lı',
  'intervalName.augmented-fifth': 'Artık 5\'li',
  'intervalName.major-sixth': 'Büyük 6\'lı',
  'intervalName.diminished-seventh': 'Eksik 7\'li',
  'intervalName.minor-seventh': 'Küçük 7\'li',
  'intervalName.major-seventh': 'Büyük 7\'li',
  'intervalName.octave': 'Oktav',
  'intervalName.minor-ninth': 'Küçük 9\'lu',
  'intervalName.major-ninth': 'Büyük 9\'lu',
  'intervalName.perfect-eleventh': 'Tam 11\'li',
  'intervalName.major-thirteenth': 'Büyük 13\'lü',
  'intervalName.tritone': 'Triton',
  'intervalQuality.perfect': 'Tam',
  'intervalQuality.major': 'Büyük',
  'intervalQuality.minor': 'Küçük',
  'intervalQuality.augmented': 'Artık',
  'intervalQuality.diminished': 'Eksik',
  'noteValue.whole': 'Birlik nota',
  'noteValue.half': 'İkilik nota',
  'noteValue.quarter': 'Dörtlük nota',
  'noteValue.eighth': 'Sekizlik nota',
  'noteValue.sixteenth': 'On altılık nota',
  'noteValue.dottedHalf': 'Noktalı ikilik nota',
  'noteValue.dottedQuarter': 'Noktalı dörtlük nota',
  'noteValue.dottedEighth': 'Noktalı sekizlik nota',
  'noteValue.eighthTriplet': 'Sekizlik triole',
  'noteValue.quarterTriplet': 'Dörtlük triole',
  'noteValue.swungLong': 'Swing uzun sekizlik',
  'noteValue.swungShort': 'Swing kısa sekizlik',
  'restValue.whole': 'Birlik sus',
  'restValue.half': 'İkilik sus',
  'restValue.quarter': 'Dörtlük sus',
  'restValue.eighth': 'Sekizlik sus',
};
