/// Names shared by lessons, diagrams, and screen-reader labels.
const sharedContentEn = <String, String>{
  'intervalName.perfect-unison': 'Perfect Unison',
  'intervalName.minor-second': 'Minor 2nd',
  'intervalName.major-second': 'Major 2nd',
  'intervalName.minor-third': 'Minor 3rd',
  'intervalName.major-third': 'Major 3rd',
  'intervalName.perfect-fourth': 'Perfect 4th',
  'intervalName.augmented-fourth': 'Augmented 4th',
  'intervalName.diminished-fifth': 'Diminished 5th',
  'intervalName.perfect-fifth': 'Perfect 5th',
  'intervalName.minor-sixth': 'Minor 6th',
  'intervalName.augmented-fifth': 'Augmented 5th',
  'intervalName.major-sixth': 'Major 6th',
  'intervalName.diminished-seventh': 'Diminished 7th',
  'intervalName.minor-seventh': 'Minor 7th',
  'intervalName.major-seventh': 'Major 7th',
  'intervalName.octave': 'Octave',
  'intervalName.minor-ninth': 'Minor 9th',
  'intervalName.major-ninth': 'Major 9th',
  'intervalName.perfect-eleventh': 'Perfect 11th',
  'intervalName.major-thirteenth': 'Major 13th',
  'intervalName.tritone': 'Tritone',
  'intervalQuality.perfect': 'Perfect',
  'intervalQuality.major': 'Major',
  'intervalQuality.minor': 'Minor',
  'intervalQuality.augmented': 'Augmented',
  'intervalQuality.diminished': 'Diminished',
  'noteValue.whole': 'Whole note',
  'noteValue.half': 'Half note',
  'noteValue.quarter': 'Quarter note',
  'noteValue.eighth': 'Eighth note',
  'noteValue.sixteenth': 'Sixteenth note',
  'noteValue.dottedHalf': 'Dotted half note',
  'noteValue.dottedQuarter': 'Dotted quarter note',
  'noteValue.dottedEighth': 'Dotted eighth note',
  'noteValue.eighthTriplet': 'Eighth-note triplet',
  'noteValue.quarterTriplet': 'Quarter-note triplet',
  'noteValue.swungLong': 'Swung long eighth',
  'noteValue.swungShort': 'Swung short eighth',
  'restValue.whole': 'Whole rest',
  'restValue.half': 'Half rest',
  'restValue.quarter': 'Quarter rest',
  'restValue.eighth': 'Eighth rest',
};
